### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by AbdulMiah** [AbdulMiah/Portfolio#1]
# Tasks
- [x] Add custom font "Ubuntu"
- [x] Add navigation brand
- [x] Add navigation links to About, Experience, Projects, Contact
- [x] Add light mode and dark mode buttons and functionality
- [x] Add Download CV button with functionality
- [x] Store colour theme preference
- [x] Fix bug where nav items are disappearing when collapsing and expanding menu
- [x] Change background colour
- [x] Centre items in collapsed menu

## Screenshots

**Light Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/8a7edced-a227-47d3-ba3a-44997410bc09)

**Dark Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/36ddaf36-dc0e-4aaf-9a25-b6cf2922d59f)
