### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by AbdulMiah** [AbdulMiah/Portfolio#2]
# Tasks
- [x] Add 3d character
- [x] Animate character to focus on cursor when comes in range
- [x] Add default animation to character if cursor is not in range
- [ ] Add circular web network behind 3d character
  - [x] Add links to LinkedIn and GitHub
  - [ ] Add programming languages nodes
  - [ ] Animate nodes to move around the circular web network

## Screenshots

**Light Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/4e15b2b8-957a-44d2-862e-a9e04e66ed46)

**Dark Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/e5f928ad-ccd2-489e-8b0f-bbd814ba1982)
