### ISSUE TITLE
About Me

### ISSUE THREAD

**Issue by AbdulMiah** [AbdulMiah/Portfolio#29]
# Tasks
- [x] Add model with idle animation
- [x] Add heading with description
- [x] Add interests section
   - [x] Add interests data to constants
   - [x] Create interests card
   - [x] Add hover animations to cards
   - [x] Create info popup for each interest
- [x] Add download cv button
- [x] Add socials
- [x] Add top page button
- [x] Add scroll animation
- [x] Animate interest description popup in and out

## Screenshots

**Light Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/615a0d80-9aea-4b40-a3e6-26e518a564e3)

**Dark Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/cce9d1c4-350e-4108-87d1-3fbbd3c2855b)
