### ISSUE TITLE
Professional Experience

### ISSUE THREAD

**Issue by AbdulMiah** [AbdulMiah/Portfolio#3]
# Tasks
- [x] Add timeline
- [x] Add experience card
  - [x] Add relevant props for job title, company name, location, description, skills
- [x] Store company logos
- [x] Update favicon
- [x] Add hyperlink to company name to redirect to official website
- [x] Implement section wrapper
   - Timestamp 1:19:00
- [x] Add description data 

## Screenshots

**Light Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/b381381e-5cb4-45a8-b4f9-e38a813db70c)

**Dark Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/6ccaeb04-1150-4712-bff0-670453cb1223)
