### ISSUE TITLE
Projects List

### ISSUE THREAD

**Issue by AbdulMiah** [AbdulMiah/Portfolio#34]
# Tasks
- [x] Add `show more` button below My Projects Section
- [x] When show button is clicked, navigate to new page `/project/all`
- [x] Add project cards in a grid of three columns
- [x] Fix `My Project` heading in Mobile view
- [x] Collapse menu when switching between light and dark mode
- [x] Add short description and long description for projects
- [x] Add the rest of the projects data
- [x] Remove show project cards whileInView
- [x] Add close button to modal
   - [x] Add tooltips
- [x] Fix skill buttons retaining their scaled size even after being hovered over
- [x] Initial loading screen
