### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by AbdulMiah** [AbdulMiah/Portfolio#38]
# Tasks

- [ ] Fix project demo videos not playing first time
- [ ] Fix project detail pages crashing when refreshed
- [x] Create contact form
- [x] Set up email service - emailJs
- [x] Add form validation - disable send message by default
- [x] Add email success message
- [x] Limit user to 1 email per session - disable send message
- [ ] Add 3D model of retro rotary telephone with ringing animation. 
    - Will have to learn blender animations
