### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by AbdulMiah** [AbdulMiah/Portfolio#4]
# Tasks
- [x] Add projects card
  - [x] Add relevant props for project id, project title, project link, description, skills
  - [x] Add carousal for images
- [x] Add a type for Project and Experience
- [x] Add custom scroll bar
- [x] Add icons to skills
- [x] ~~Change selected nav item when scroll between sections~~
   - [Reference](https://stackoverflow.com/questions/76400197/react-update-url-anchor-when-scrolling-to-a-section-with-this-anchor)

## Screenshots

**Light Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/bc80c333-a4f1-47e7-9e91-181ae8a47b53)

**Dark Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/de5d4d02-e594-4287-b0df-508d97c3eff0)
