### ISSUE TITLE
Minor bugfixes and features

### ISSUE THREAD

**Issue by AbdulMiah** [AbdulMiah/Portfolio#40]
# Tasks
- [ ] Fix project demo videos not playing first time
- [ ] Fix project detail pages crashing when refreshed
- [ ] Animate retro rotary telephone with ringing animation - blender
- [ ] Fix modals getting enlarged when scrolling on initial page load
- [ ] Change selected nav item when scroll between sections
   - [Reference](https://stackoverflow.com/questions/76400197/react-update-url-anchor-when-scrolling-to-a-section-with-this-anchor)
- [ ] Resolve lint errors and warnings
- [x] Add character limit to message field
- [ ] Save `isEmailSent` to localStorage
- [x] Fix about avatar becoming bald when rotating
- [ ] Create new email for portfolio#
- [x] Limit message text area drag height
