### ISSUE TITLE
Project Details

### ISSUE THREAD

**Issue by AbdulMiah** [AbdulMiah/Portfolio#5]
# Tasks
- [x] Fix about section component being rendered early due to section being in view of landing page
- [x] Fix interest description to be in the center of the container
- [x] Change project list URL to `/project/all`
- [x] Fix back button on `ProjectList` being with width of screen
- [ ] Fix modals getting enlarged when scrolling on initial page load
- [x] Add back button to go back to project section on main page
- [x] _Pass in project data into props to populate this page_
- [x] Add GitHub link to project button
- [x] Screen record video of all projects
- [x] Add 3d model with a video texture of the project
  - [x] Add spin interaction to 3d model
- [x] Add screenshots underneath project details
- [x] Add next project component to navigate between different projects
- [x] Add "back to top" button
- [x] Initial loading screen
- [ ] Change selected nav item when scroll between sections
   - [Reference](https://stackoverflow.com/questions/76400197/react-update-url-anchor-when-scrolling-to-a-section-with-this-anchor)

## Screenshots

**Light Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/c146434a-c422-4aff-b446-4f72e8b9b0d3)

**Dark Mode**

![image](https://github.com/AbdulMiah/Portfolio/assets/51327213/75c42f95-d134-4234-8791-f378a84fe6bf)
